package creator

import (
	"io"
	"os"

	"github.com/spf13/afero"

	"github.com/giantswarm/kubectl-gs/v6/internal/gitops/filesystem/modifier"
	"github.com/giantswarm/kubectl-gs/v6/internal/gitops/metadata"
)

const (
	defaultDirPerm  = 0755
	defaultFilePerm = 0600
)

type Creator struct {
	dryRun        bool
	fs            *afero.Afero
	fsObjects     []*FsObject
	metadataLayer *metadata.Layer
	path          string
	postModifiers map[string]modifier.Modifier
	preValidators map[string]func(*afero.Afero, string) error
	stdout        io.Writer
	writeMetadata bool
}

type CreatorConfig struct {
	DryRun    bool
	FsObjects []*FsObject

	// Fs is the file system to work on. Defaults to the OS file system when
	// left empty; tests inject an in-memory one.
	Fs afero.Fs

	// MetadataLayer, when set, is recorded in the repository metadata file as
	// having been generated by this run. Implies WriteMetadata.
	MetadataLayer *metadata.Layer

	Path          string
	PostModifiers map[string]modifier.Modifier
	PreValidators map[string]func(*afero.Afero, string) error
	Stdout        io.Writer

	// WriteMetadata creates or refreshes the repository metadata file at the
	// repository root, even when no layer is recorded. Used by `gitops init`,
	// which sets up a repository without generating a layer.
	WriteMetadata bool
}

type FsObject struct {
	Data         []byte
	Permission   os.FileMode
	RelativePath string
}
