apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: gs
spec:
  version: {{ .TagName }}
  homepage: https://github.com/giantswarm/kubectl-gs
  shortDescription: Handle custom resources with Giant Swarm
  description: |
    Simplifies creating clusters and node pools via Giant Swarm
    management clusters, as well as installing app catalogs and apps.
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/giantswarm/kubectl-gs/releases/download/{{ .TagName }}/kubectl-gs-darwin-amd64" .TagName }}
    bin: kubectl-gs
  - selector:
      matchLabels:
        os: darwin
        arch: arm64
    {{addURIAndSha "https://github.com/giantswarm/kubectl-gs/releases/download/{{ .TagName }}/kubectl-gs-darwin-arm64" .TagName }}
    bin: kubectl-gs
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/giantswarm/kubectl-gs/releases/download/{{ .TagName }}/kubectl-gs-linux-amd64" .TagName }}
    bin: kubectl-gs
  - selector:
      matchLabels:
        os: linux
        arch: arm64
    {{addURIAndSha "https://github.com/giantswarm/kubectl-gs/releases/download/{{ .TagName }}/kubectl-gs-linux-arm64" .TagName }}
    bin: kubectl-gs
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    {{addURIAndSha "https://github.com/giantswarm/kubectl-gs/releases/download/{{ .TagName }}/kubectl-gs-windows-amd64.exe" .TagName }}
    bin: kubectl-gs.exe
  - selector:
      matchLabels:
        os: windows
        arch: arm64
    {{addURIAndSha "https://github.com/giantswarm/kubectl-gs/releases/download/{{ .TagName }}/kubectl-gs-windows-arm64.exe" .TagName }}
    bin: kubectl-gs.exe
