package check

import (
	"bytes"
	"context"
	"strings"
	"testing"

	"github.com/spf13/afero"
	"github.com/spf13/cobra"

	"github.com/giantswarm/kubectl-gs/v6/internal/gitops/metadata"
)

const (
	testRepo = "/repo"
	testMC   = "management-clusters/demomc"
	testOrg  = testMC + "/organizations/demoorg"
	testWC   = testOrg + "/workload-clusters/demowc"
)

// newTestCommand mimics the cobra tree the runner reads its inherited flags
// from: `gitops` owns --local-path and --dry-run, `check` is its child.
func newTestCommand(repoPath string, dryRun bool) *cobra.Command {
	parent := &cobra.Command{Use: "gitops"}
	parent.PersistentFlags().String("local-path", ".", "")
	parent.PersistentFlags().Bool("dry-run", false, "")
	_ = parent.PersistentFlags().Set("local-path", repoPath)
	if dryRun {
		_ = parent.PersistentFlags().Set("dry-run", "true")
	}

	child := &cobra.Command{Use: "check"}
	parent.AddCommand(child)

	return child
}

func newTestRunner(fs afero.Fs, adopt bool, out *bytes.Buffer) *runner {
	return &runner{
		flag:   &flag{Adopt: adopt},
		fs:     &afero.Afero{Fs: fs},
		stdout: out,
		stderr: out,
	}
}

// generatedRepo lays out a repository as `kubectl gs gitops` would have.
func generatedRepo(t *testing.T) afero.Fs {
	t.Helper()

	fs := &afero.Afero{Fs: afero.NewMemMapFs()}

	dirs := []string{
		testWC + "/mapi/apps",
	}
	for _, d := range dirs {
		err := fs.MkdirAll(testRepo+"/"+d, 0755)
		if err != nil {
			t.Fatalf("unexpected error: %s", err)
		}
	}

	return fs
}

func Test_Check_ReportsUpToDate(t *testing.T) {
	fs := generatedRepo(t)
	out := new(bytes.Buffer)

	md := metadata.New()
	md.Upsert(metadata.Layer{Kind: metadata.LayerManagementCluster, Path: testMC})
	err := metadata.Save(&afero.Afero{Fs: fs}, testRepo, md)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	err = newTestRunner(fs, false, out).run(context.Background(), newTestCommand(testRepo, false), nil)
	if err != nil {
		t.Fatalf("expected an up to date repository to pass, got: %s", err)
	}

	if !strings.Contains(out.String(), "up to date") {
		t.Errorf("expected the report to say the repository is up to date, got:\n%s", out.String())
	}
}

func Test_Check_FailsOnDrift(t *testing.T) {
	fs := generatedRepo(t)
	out := new(bytes.Buffer)

	md := metadata.New()
	md.Upsert(metadata.Layer{Kind: metadata.LayerManagementCluster, Path: testMC})
	// Pretend the layer was generated by an older kubectl-gs.
	md.Layers[0].StructureVersion = metadata.StructureVersion - 1
	err := metadata.Save(&afero.Afero{Fs: fs}, testRepo, md)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	err = newTestRunner(fs, false, out).run(context.Background(), newTestCommand(testRepo, false), nil)
	if err == nil {
		t.Fatal("expected an outdated repository to fail, so the command is usable as a CI check")
	}

	if !strings.Contains(out.String(), "outdated") {
		t.Errorf("expected the report to flag the outdated layer, got:\n%s", out.String())
	}
	if !strings.Contains(out.String(), "1 layer(s) out of sync") {
		t.Errorf("expected a summary of what is out of sync, got:\n%s", out.String())
	}
}

func Test_Check_FailsOnRepositoryLevelDrift(t *testing.T) {
	fs := generatedRepo(t)
	out := new(bytes.Buffer)

	// A repository that only ever had `gitops init` run against it records no
	// layers, but can still fall behind.
	md := metadata.New()
	md.StructureVersion = metadata.StructureVersion - 1
	err := metadata.Save(&afero.Afero{Fs: fs}, testRepo, md)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	err = newTestRunner(fs, false, out).run(context.Background(), newTestCommand(testRepo, false), nil)
	if err == nil {
		t.Fatal("expected a repository behind on the structure version to fail")
	}
	if !strings.Contains(out.String(), "No layers recorded yet") {
		t.Errorf("expected the report to note there are no layers, got:\n%s", out.String())
	}
}

func Test_Check_PointsAtAdoptWhenUntracked(t *testing.T) {
	fs := generatedRepo(t)
	out := new(bytes.Buffer)

	err := newTestRunner(fs, false, out).run(context.Background(), newTestCommand(testRepo, false), nil)
	if err == nil {
		t.Fatal("expected an untracked repository to fail")
	}
	if !strings.Contains(err.Error(), "--adopt") {
		t.Errorf("expected the error to point at --adopt, got: %s", err)
	}
}

func Test_Check_Adopt(t *testing.T) {
	fs := generatedRepo(t)
	out := new(bytes.Buffer)

	err := newTestRunner(fs, true, out).run(context.Background(), newTestCommand(testRepo, false), nil)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	md, err := metadata.Load(&afero.Afero{Fs: fs}, testRepo)
	if err != nil {
		t.Fatalf("expected adoption to write the metadata file: %s", err)
	}

	expected := map[string]string{
		metadata.LayerManagementCluster: testMC,
		metadata.LayerOrganization:      testOrg,
		metadata.LayerWorkloadCluster:   testWC,
	}
	if len(md.Layers) != len(expected) {
		t.Fatalf("expected %d layers, got %d", len(expected), len(md.Layers))
	}
	for _, l := range md.Layers {
		if expected[l.Kind] != l.Path {
			t.Errorf("unexpected layer recorded: %s at %s", l.Kind, l.Path)
		}
	}

	// Adoption must be honest about what it cannot know.
	if !strings.Contains(out.String(), "not detectable") {
		t.Errorf("expected adoption to warn that earlier drift is invisible, got:\n%s", out.String())
	}

	// The repository is tracked now, so a plain check has to pass.
	err = newTestRunner(fs, false, new(bytes.Buffer)).run(context.Background(), newTestCommand(testRepo, false), nil)
	if err != nil {
		t.Errorf("expected the adopted repository to check out clean, got: %s", err)
	}
}

func Test_Check_AdoptDryRunWritesNothing(t *testing.T) {
	fs := generatedRepo(t)
	out := new(bytes.Buffer)

	err := newTestRunner(fs, true, out).run(context.Background(), newTestCommand(testRepo, true), nil)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	exists, err := afero.Exists(fs, metadata.FilePath(testRepo))
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}
	if exists {
		t.Error("a dry run must not write the metadata file")
	}
	if !strings.Contains(out.String(), metadata.Kind) {
		t.Errorf("expected the dry run to print what it would write, got:\n%s", out.String())
	}
}

func Test_Check_AdoptIsIdempotent(t *testing.T) {
	fs := generatedRepo(t)

	err := newTestRunner(fs, true, new(bytes.Buffer)).run(context.Background(), newTestCommand(testRepo, false), nil)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	out := new(bytes.Buffer)
	err = newTestRunner(fs, true, out).run(context.Background(), newTestCommand(testRepo, false), nil)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	if !strings.Contains(out.String(), "Nothing to adopt") {
		t.Errorf("expected a second adoption to be a no-op, got:\n%s", out.String())
	}
}

// Adopting into a repository that is already tracked must fill the gaps
// without bumping what is already recorded, or drift would be erased.
func Test_Check_AdoptDoesNotEraseDrift(t *testing.T) {
	fs := generatedRepo(t)

	md := metadata.New()
	md.Upsert(metadata.Layer{Kind: metadata.LayerManagementCluster, Path: testMC})
	md.Layers[0].StructureVersion = metadata.StructureVersion - 1
	err := metadata.Save(&afero.Afero{Fs: fs}, testRepo, md)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	err = newTestRunner(fs, true, new(bytes.Buffer)).run(context.Background(), newTestCommand(testRepo, false), nil)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	reloaded, err := metadata.Load(&afero.Afero{Fs: fs}, testRepo)
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	for _, l := range reloaded.Layers {
		if l.Path == testMC && l.StructureVersion != metadata.StructureVersion-1 {
			t.Errorf("adoption must not bump an already recorded layer, got version %d", l.StructureVersion)
		}
	}

	if len(reloaded.Layers) < 3 {
		t.Errorf("expected adoption to add the untracked layers, got %d", len(reloaded.Layers))
	}
}
