name: Send workflow usage metrics
on: pull_request

jobs:
  usage:
    runs-on: ubuntu-latest
    steps:
      - name: Send data to Loki
        env:
          GRAFANA_API_TOKEN: ${{ secrets.GRAFANA_API_TOKEN }}
          GRAFANA_CLOUD_LOKI_URL: ${{ vars.GRAFANA_CLOUD_LOKI_URL }}
          GRAFANA_CLOUD_USER: ${{ secrets.GRAFANA_CLOUD_USER }}
        run: |
          tod_nanos=$( date +%s)000000000
          curl -u "${GRAFANA_CLOUD_USER}:${GRAFANA_API_TOKEN}" \
            --include \
            --header "Content-Type: application/json" \
            --request POST \
            --silent "${GRAFANA_CLOUD_LOKI_URL}" \
            --data-raw "{\"streams\": [{ \"stream\": {\
              \"service_name\": \"github-workflows\", \"level\": \"info\"}, \"values\": [ [ \"$tod_nanos\", \"\
          actor=\\\"$GITHUB_ACTOR\\\" \
          actor_id=\\\"$GITHUB_ACTOR_ID\\\" \
          actor_triggering=\\\"$GITHUB_TRIGGERING_ACTOR\\\" \
          event_name=\\\"$GITHUB_EVENT_NAME\\\" \
          job_id=\\\"$GITHUB_JOB\\\" \
          sha=\\\"$GITHUB_SHA\\\" \
          ref=\\\"$GITHUB_REF\\\" \
          ref_name=\\\"$GITHUB_REF_NAME\\\" \
          ref_type=\\\"$GITHUB_REF_TYPE\\\" \
          repository=\\\"$GITHUB_REPOSITORY\\\" \
          repository_id=\\\"$GITHUB_REPOSITORY_ID\\\" \
          repository_owner=\\\"$GITHUB_REPOSITORY_OWNER\\\" \
          run_attempt=\\\"$GITHUB_RUN_ATTEMPT\\\" \
          run_id=\\\"$GITHUB_RUN_ID\\\" \
          run_number=\\\"$GITHUB_RUN_NUMBER\\\" \
          github_server_url=\\\"$GITHUB_SERVER_URL\\\" \
          workflow_name=\\\"$GITHUB_WORKFLOW\\\" \
          workflow_ref=\\\"$GITHUB_WORKFLOW_REF\\\" \
          workflow_sha=\\\"$GITHUB_WORKFLOW_SHA\\\" \
          runner_arch=\\\"$RUNNER_ARCH\\\" \
          runner_environment=\\\"$RUNNER_ENVIRONMENT\\\" \
          runner_name=\\\"$RUNNER_NAME\\\" \
          runner_os=\\\"$RUNNER_OS\\\" \
          url=\\\"$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID\\\" \
          \" ]]}]}"
      - name: Show timing data
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID/timing
