name: Scorecard supply-chain security
on:
  branch_protection_rule:
  schedule:
    - cron: '15 15 15 * *'
  push:
    branches: [ "main", "master" ]
  workflow_dispatch: {}

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    uses: giantswarm/github/.github/workflows/rw-oss-scorecard.yaml@add-reusable-workflow
