name: Scorecard supply-chain security
on:
  branch_protection_rule:
  schedule:
    - cron: '15 15 15 * *'
  push:
    branches:
      - main
  workflow_dispatch: {}

# Declare default permissions as read only.
permissions: read-all

jobs:
  analysis:
    uses: giantswarm/github/.github/workflows/rw-oss-scorecard.yaml@9687420dcf71de454ed71d9a576da27194b5967a
